
// Tags
export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const CREATE_TAG = "CREATE_TAG";
export const UPDATED_TAG = "UPDATED_TAG";
export const FIND_SINGLE_TAG = "FIND_SINGLE_TAG";
export const DELETE_SINGLE_TAG = "DELETE_SINGLE_TAG";
export const CHANGE_STATUS_TAG_BUTTON = "CHANGE_STATUS_TAG_BUTTON";




// Sub Cats

export const GET_ALL_SUBCATS = "GET_ALL_SUBCATS";
export const CREATE_SUBCATS = "CREATE_SUBCATS";
export const UPDATED_SUBCATS = "UPDATED_SUBCATS";
export const FIND_SINGLE_SUBCATS = "FIND_SINGLE_SUBCATS";
export const DELETE_SINGLE_SUBCATS = "DELETE_SINGLE_SUBCATS";
export const CHANGE_STATUS_SUBCATS_BUTTON = "CHANGE_STATUS_SUBCATS_BUTTON";



// Cat
export const GET_ALL_CATS = "GET_ALL_CATS";
export const CREATE_CATS = "CREATE_CATS";
export const UPDATED_CATS = "UPDATED_CATS";
export const FIND_SINGLE_CATS = "FIND_SINGLE_CATS";
export const DELETE_SINGLE_CATS = "DELETE_SINGLE_CATS";
export const CHANGE_STATUS_CATS_BUTTON = "CHANGE_STATUS_CATS_BUTTON";



// PRODUCTS

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const UPDATED_PRODUCTS = "UPDATED_PRODUCTS";
export const FIND_SINGLE_PRODUCTS = "FIND_SINGLE_PRODUCTS";
export const DELETE_SINGLE_PRODUCTS = "DELETE_SINGLE_PRODUCTS";
export const CHANGE_STATUS_PRODUCTS_BUTTON = "CHANGE_STATUS_PRODUCTS_BUTTON";


